"""create issue dependencies table

Revision ID: 08fc14f084cd
Revises: c80c444d91e8
Create Date: 2026-07-19 01:41:42.851330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fc14f084cd'
down_revision: Union[str, Sequence[str], None] = 'c80c444d91e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_issue_id', sa.Integer(), nullable=False),
    sa.Column('target_issue_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'RELATED', 'DUPLICATE', name='dependencytype'), nullable=False),
    sa.ForeignKeyConstraint(['source_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_issue_id', 'target_issue_id', 'dependency_type', name='uq_issue_dependency')
    )
    op.create_index(op.f('ix_issue_dependencies_id'), 'issue_dependencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_dependencies_id'), table_name='issue_dependencies')
    op.drop_table('issue_dependencies')
    # ### end Alembic commands ###
