"""add created_at to issue dependencies

Revision ID: c7e0fa4689cf
Revises: 08fc14f084cd
Create Date: 2026-07-19 01:47:58.627625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e0fa4689cf'
down_revision: Union[str, Sequence[str], None] = '08fc14f084cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_dependencies', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_dependencies', 'created_at')
    # ### end Alembic commands ###
