"""add milestone to issues

Revision ID: c80c444d91e8
Revises: aa34db44d7a7
Create Date: 2026-07-19 00:13:47.045436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80c444d91e8'
down_revision: Union[str, Sequence[str], None] = 'aa34db44d7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'milestone_id')
    # ### end Alembic commands ###
